### ISSUE TITLE
BLS12-381 Specification 

### ISSUE THREAD

**Issue by ChainSafeSystems** [ChainSafe/bls-js#1]
https://github.com/ethereum/eth2.0-specs/pull/141

- [x] - preliminary research gathering
- [ ] - skeleton code
- [ ] - stuff here

**Comment by Mikerah** [comment]
Closing since no details.

**Comment by ChainSafeSystems** [comment]
Don't worry this is for @noot, who is implementing it. Sorry accidentally deleted the previous comment.

**Comment by noot** [comment]
going to link some useful articles and papers:
https://medium.com/cryptoadvance/bls-signatures-better-than-schnorr-5a7fe30ea716
https://github.com/phoreproject/bls implementation in go
https://z.cash/blog/new-snark-curve/ specifications

pairings stuff:
https://medium.com/coinmonks/having-fun-with-bn-curves-37fb5b816f67
https://eprint.iacr.org/2005/133.pdf pairing-friendly elliptic curves
https://www.cosic.esat.kuleuven.be/ecc2013/files/pierrick_gaudry_2.pdf pairing-friendly elliptic curves ppt

**Comment by ChainSafeSystems** [comment]
I am going to make a preliminary checklist in the top description, please edit it as necessary.

**Comment by Mikerah** [comment]
This is not relevant for this repo and there's is a BLS12-381 in milagro-crypto-js. There has been a lot of benchmarking of milagro code and it seems to be fairing well. So, there's is no need to reimplement it.

**Comment by noot** [comment]
is BLS381 the same as BLS12-381? I only see BLS381 in milagro js.

**Comment by Mikerah** [comment]
If you look through the code, yes. In the future, these conversations should occur in our gitter channel.
