### ISSUE TITLE
Use more permissive license

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/bls-js#15]
Since this is a utility library and really just a thin wrapper around herumi's work, it seems like overkill to use the GPL.

Also, we want to pull out the eth2 spec tester, created https://github.com/ChainSafe/bls-js/pull/14, and that small utility should not be licensed under GPL.

I've mentioned this in https://github.com/ChainSafe/lodestar/issues/70 but GPL is very aggressive for the web and really limits the reach of our code in the wider javascript community.

**Comment by GregTheGreek** [comment]
You're totally correct all libraries should be under apache/mit , only the actual clients should be licensed under GPL

**Comment by wemeetagain** [comment]
resolved by #16
