### ISSUE TITLE
Not published on npm?

### ISSUE THREAD

**Issue by prestonvanloon** [ChainSafe/bls-js#30]
I tried to install as directed by the README
```
npm install bls-js

npm ERR! code E404
npm ERR! 404 Not Found: bls-js@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/preston/.npm/_logs/2019-05-25T15_58_48_278Z-debug.log
```

**Comment by prestonvanloon** [comment]
Looks like it is published as `@chainsafe/bls-js` but the README is incorrect.

**Comment by GregTheGreek** [comment]
@prestonvanloon Woops, thanks for catching that!

**Comment by ubltroll** [comment]
I got these errors when trying to install via npm
Seems that there is something wrong with the config setting
------------------------------------------
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "@chainsafe/bls-js" under a package
npm ERR! also called "@chainsafe/bls-js". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/troll/.npm/_logs/2019-05-26T10_48_55_266Z-debug.log

**Comment by mpetrunic** [comment]
@ubltroll Are you trying to setup dev environment for library or using library in on of your own projects?

**Comment by mpetrunic** [comment]
I guess we will close this
